# rule identifiers to exclude from running
disabled_rules:
  - discarded_notification_center_observer
  - generic_type_name
  - implicit_getter
  - dynamic_inline
  - for_where
  - unused_closure_parameter
  - identifier_name
  - trailing_whitespace
  - weak_delegate
  - unused_optional_binding
  - syntactic_sugar


# rule identifiers to opt in
opt_in_rules:
  - force_unwrapping


# special configuration for rules 
function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 400
  error: 1000

colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

large_tuple:
  warning: 2
  error: 3

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: false

line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 300
  error: 500

